version: '3'
services:
  pro1:
    image: apn2993/pro1repo:latest
    ports:
      - "91:80"
    volumes:
      - "pro1svol"

  pro2:
    image: apn2993/pro2repo:latest 
    ports:
      - "92:80"
    volumes:
      - "pro2vol"


  pro3: apn2993/pro3repo:latest
    image: 
    ports:
      - "93:80"
    volumes:
      - "pro3vol"

  pro4: apn2993/pro4repo:latest
    image: 
    ports:
      - "94:80"
    volumes:
      - "pro4vol"
